name: natusic # Name of the Catalog Entry
description: |
  # Description of the Catalog Entry
version: 0 # Version of the Catalog to be used
category: All# Category to be used for searching catalog entries
maintainer: Natusik # The maintainer of the catalog entry
license: # The license
projectURL: # A URL related to the catalog entry
